#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀🚀 Preparing your project before committing... 👷🚧"


echo "🧽🧽🧽 Formatting with Prettier"
bun format || {
  echo "❌❌❌ Prettier Format Failed. Run bun format.";
  false;
}


echo "🧹🧹🧹 Checking ESLint"
bun lint || {
  echo "🤢🤢🤢 ESLint Check Failed. Make the required change above.";
  false;
}


echo "👷👷👷 Building your project"
bun run build || {
  echo "🏨🏨🏨 Build Failed. Oops building failed checkout what is the problem.";
  false;
}

echo "🧪🧪🧪 Testing your project 🔬🔬🔬"
bun run test || {
  echo "🧪🧪🧪 Test Failed. Nah man you're didnt that good.";
  false;
}


echo "🎉🎉🎉 You win. Committing this now. 🎉🎉🎉"